### ISSUE TITLE
Rename pages to full name

### ISSUE THREAD

**Issue by notkevin888** [sharikak54/sharikak54.github.io#13]
Currently, pages are titled by the URL/short name - eg, it's called `Lkite_moth | OBL: An Intuitive Guide`:
![2021-09-06 lkite_moth title](https://user-images.githubusercontent.com/8520179/132178567-494cce09-beec-4170-bc17-0cd458ad5696.png)

It'd be slightly better for them to use the full name (`Left Kite / Moth | OBL: An Intuitive Guide`) instead; I'm guessing there's a way to modify something in https://github.com/sharikak54/sharikak54.github.io/blob/main/_layouts/case.html, but haven't looked into it yet.

**Comment by sharikak54** [comment]
Jekyll Front Matter doesn't take variables, so titles like "Case: {{page.name}}" were failing.  I've individually set the title on each page in a collection, so this should now be fixed.
